import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Kotta_One, Krona_One } from 'next/font/google'
import { api } from "~/utils/api";

import localFont from 'next/font/local'
import React from "react";

const authenticSansCondensed = localFont({
  src: [
    {
      path: './fonts/authentic-sans-condensed-60.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/authentic-sans-condensed-90.woff2',
      weight: '500',
      style: 'italic',
    },
    {
      path: './fonts/authentic-sans-condensed-130.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/authentic-sans-condensed-150.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
})
const authenticSans = localFont({
  src: [
    {
      path: './fonts/authentic-sans-60.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/authentic-sans-90.woff2',
      weight: '500',
      style: 'italic',
    },
    {
      path: './fonts/authentic-sans-130.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/authentic-sans-150.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
})

const kotta = Kotta_One({
  weight: '400',
  subsets: ['latin']
})
const krona = Krona_One({
  weight: '400',
  subsets: ['latin']
})
const Home: NextPage = () => {
  const [colorSystem, setColorSystem] = React.useState<string>("Pantone");

  const handleColorSystemChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    console.log(e.target.value);

    setColorSystem(e.target.value);
  }

  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const colors = [
    { name: "PMS 100", hex: "#FEDD00" },
    { name: "PMS 101", hex: "#FEDD38" },
    { name: "PMS 102", hex: "#FDB813" },
    { name: "PMS 103", hex: "#FDA600" },
    { name: "PMS 104", hex: "#C28F00" },
    { name: "PMS 105", hex: "#AF8400" },
    { name: "PMS 106", hex: "#897322" },
    { name: "PMS 107", hex: "#FEDD5C" },
    { name: "PMS 108", hex: "#FDBE2D" },
    { name: "PMS 109", hex: "#FFA300" },
    { name: "PMS 110", hex: "#D57600" },
    { name: "PMS 111", hex: "#AF6D04" },
    { name: "PMS 112", hex: "#7D5109" },
    { name: "PMS 113", hex: "#FFD87D" },
    { name: "PMS 114", hex: "#FFC800" },
    { name: "PMS 115", hex: "#FFB500" },
    { name: "PMS 116", hex: "#EAAA00" },
    { name: "PMS 117", hex: "#B58500" },
    { name: "PMS 118", hex: "#9A7500" },
    { name: "PMS 119", hex: "#6D4F47" },
    { name: "PMS 120", hex: "#FFC87D" },
    { name: "PMS 121", hex: "#FFA64F" },
    { name: "PMS 122", hex: "#FF8C00" },
    { name: "PMS 123", hex: "#FF7F00" },
    { name: "PMS 124", hex: "#E66F00" },
    { name: "PMS 125", hex: "#B85C00" },
    { name: "PMS 126", hex: "#7D3F00" },
    { name: "PMS 127", hex: "#FFB347" },
    { name: "PMS 128", hex: "#FF8F1C" },
    { name: "PMS 129", hex: "#FF6F00" },
    { name: "PMS 130", hex: "#D15B00" },
    { name: "PMS 131", hex: "#AF5200" },
    { name: "PMS 132", hex: "#7D3A00" },
    { name: "PMS 133", hex: "#FFC4A8" },
    { name: "PMS 134", hex: "#FF9C5B" },
    { name: "PMS 135", hex: "#FF7F4F" },
    { name: "PMS 136", hex: "#FF671F" },
    { name: "PMS 137", hex: "#D15B00" },
    { name: "PMS 138", hex: "#A34700" },
  ];



  return (
    <>
      <Head>
        <title>Book of Color</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overlay pointer-events-none inset-0 absolute w-full h-full z-[9998] background-image-[url('/images/grain.png')] bg-cover bg-center bg-no-repeat opacity-50"></div>
      <main className={`flex flex-col h-screen ${authenticSans.className}`}>
        {/* Navbar */}
        <nav className=" bg-gray-800 border-b-2 border-black bg-white">
          <div className={`px-4 py-2 flex items-center justify-between`}>
            <span className={`text-3xl ${krona.className}`}>Book of Color</span>
            <ul className="flex space-x-4">
              {/* <li><a href="#" className="hover:text-gray-300">Home</a></li>
              <li><a href="#" className="hover:text-gray-300">About</a></li>
              <li><a href="#" className="hover:text-gray-300">Contact</a></li> */}
            </ul>
          </div>
        </nav>

        <div className="flex h-full md:flex-row flex-col overflow-hidden">
          {/* Sidebar */}
          <div className="bg-gray-100 md:border-r md:border-r-2 border-black py-5 md:w-[20%] md:min-w-[200px] font-bold">
            <select className="block w-full border border-gray-800 py-2 px-2 rounded mb-4 w-11/12 m-auto" value={colorSystem} onChange={handleColorSystemChange}>
              <option value="Pantone">Pantone</option>
              <option value="Web">Web</option>
              <option value="U.S. Airforce">U.S. Airforce</option>
            </select>
            <ul className="text-xl">
              <li><a href="#" className="hover:border-l-2  transition-all block px-4 py-2 hover:bg-gray-200  px-4 py-2 border border-l-4 border-l-black">color profiles</a></li>
              <li><a href="#" className="hover:border-l-2 border-l-0 border-l-black transition-all block px-4 py-2 hover:bg-gray-200  px-4 py-2  border">palettes</a></li>
              <li><a href="#" className="hover:border-l-2 border-l-0 border-l-black transition-all block px-4 py-2 hover:bg-gray-200  px-4 py-2  border">favorites</a></li>
              <li><a href="#" className="hover:border-l-2 border-l-0 border-l-black transition-all block px-4 py-2 hover:bg-gray-200  px-4 py-2  border">mixer</a></li>
            </ul>
          </div>

          {/* Main Content */}
          <div className="flex-1 overflow-y-scroll bg-gray-50">
            <div className="container mx-auto px-4">
              <section className="py-4">
                <div className="container mx-auto px-4">
                  <h1 className="text-4xl font-bold">{colorSystem}</h1>
                  <div className="container mx-auto my-10">
                    <div className="flex flex-wrap mx-4 my-8">
                      {colors.map((color) => (
                        <div className="group cursor-pointer flex flex-col items-center text-center" key={color.name} title={color.name} data-color-name={color.name} data-color-hex={color.hex} data-color-type="hexa-decimal-rgb">
                          <div
                            key={color.hex}
                            style={{ backgroundColor: color.hex }}
                            className="flex-shrink-0 h-12 w-12 rounded-md m-2 z-[9999]"
                          ></div>
                          <span className="group-hover:opacity-100 opacity-0 transition-all text-sm font-bold text-gray-800">{color.name}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt elit euismod lectus mattis, at bibendum quam sodales. Sed non orci ipsum. Fusce quis dolor eget quam ullamcorper ultrices. Donec posuere laoreet tellus eu rhoncus. Nulla facilisi. Ut id dui et arcu congue luctus. Praesent suscipit arcu vel feugiat iaculis.</p>
                  <p>Etiam eget enim risus. Suspendisse euismod ex velit, vel fringilla neque tincidunt vel. Proin vehicula turpis ac nisi tempor, eget varius tellus facilisis. Sed dictum sapien risus, eu pretium ipsum commodo eu. Donec sit amet sapien eros. Nulla facilisi. Donec auctor fringilla libero, nec scelerisque odio commodo nec. Mauris vel mi sed arcu faucibus rutrum vel ac est.</p>
                  <p>In et dapibus ante, non vulputate dolor. Mauris placerat, massa non pretium sodales, massa nisi euismod eros, ac dictum dolor mauris a justo. Vestibulum pulvinar augue ut nunc rhoncus, vel ullamcorper arcu pharetra. Duis congue auctor nulla eu commodo. Nullam auctor augue quis purus commodo bibendum. Curabitur in ultrices purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
                  <p>Sed elementum eu odio ac bibendum. Etiam sed ex quis justo scelerisque egestas. Vestibulum consectetur diam quis diam gravida laoreet. Donec venenatis risus ac augue euismod feugiat. Curabitur tristique orci id eleifend pellentesque. Vivamus elementum, mi sit amet euismod gravida, tellus velit sagittis eros, sed ullamcorper felis lacus at nunc. Ut vestibulum sapien in dolor vestibulum tincidunt.</p>
                  <p>Aliquam a lacus quam. Morbi sit amet magna at neque facilisis lacinia quis vel ipsum. Sed sit amet mi iaculis, tincidunt massa eget, sollicitudin lorem. Sed tincidunt quam id mauris venenatis ullamcorper. Aenean sed nibh sit amet nulla ultrices fermentum. Nam a tincidunt elit. Sed in eros eget tellus malesuada varius vel sit amet ipsum.</p>
                  <p>Cras suscipit, eros et facilisis euismod, odio nulla varius elit, a sollicitudin metus felis sit amet tortor. Donec vel enim at velit sollicitudin malesuada. Proin vel feugiat ex, a malesuada mauris. Aliquam ac purus magna. Nunc at erat vel dolor suscipit lobortis. In sagittis libero et purus imperdiet, nec malesuada quam imperdiet. Vivamus at sapien quis ex ullamcorper fermentum.</p>
                  <p>Integer et justo vitae tellus eleifend venenatis. Vestibulum sit amet nunc sed sapien imperdiet malesuada ut eu ante. Praesent sed massa ornare, dapibus eros quis, laoreet velit. Integer ultricies tortor nec dolor lobortis, nec consectetur enim dignissim. Aenean hendrerit purus ut odio pretium dignissim. Sed in sem auctor, gravida ex ac, vehicula purus. Nullam sit amet mauris a felis tincidunt tempor id vel urna. Nam feugiat volutpat elit at faucibus.</p>

                  <p>Proin vel fermentum massa. Etiam quis urna in nunc imperdiet aliquet eget ac massa. Fusce dapibus, nulla ac ornare dictum, arcu dui feugiat nisl, in facilisis purus orci eu dolor. Nam efficitur lorem a dolor accumsan, vel vestibulum nibh consectetur. Sed vitae elit in elit vestibulum malesuada eu a elit. Nullam id urna arcu. Nullam lobortis ipsum eget tellus lobortis, eu efficitur enim venenatis. Sed maximus vel augue eu vehicula.</p>
                  <p>Suspendisse mollis est quis blandit scelerisque. Suspendisse sed sapien at augue maximus faucibus. Integer semper enim quis risus posuere, vitae bibendum enim vestibulum. Nam venenatis hendrerit sapien, id cursus risus commodo quis. Nulla congue est quis lorem maximus, a consequat tellus rutrum. In vel tellus at risus consectetur placerat. Sed sollicitudin quis ipsum nec mattis. Nam in massa in erat dictum rutrum. Praesent at mauris eu lectus tincidunt laoreet sed ac nibh. Fusce tincidunt sit amet ante vel placerat. Donec id sem ac ipsum consequat tincidunt. Donec eget elit elit. Integer vestibulum elit lectus, in bibendum metus molestie non. Vestibulum dapibus varius ex, vel bibendum nisl tristique vel.</p>
                  <p>Phasellus vel nulla nec tellus sagittis feugiat. Vestibulum id nunc purus. Sed at eros sapien. Pellentesque commodo risus vel urna commodo, eget hendrerit urna dictum. Morbi tincidunt nibh sed tortor lacinia, vitae molestie tellus bibendum. Nullam nec turpis purus. Praesent porttitor, urna at commodo rutrum, massa dui interdum nulla, non sodales magna turpis vitae dui. Fusce volutpat a urna at tristique.</p>
                </div>
              </section>           </div>
          </div>
        </div>

      </main>
    </>
  );
};

export default Home;
